# Site settings
title: The Pinax Project Blog
email: developers@pinaxproject.com
description: > # this means to ignore newlines until "baseurl:"
  The Pinax project is an ecosystem of Django apps, starter projects and
  themes, taking care of many of the things sites have in common allowing you
  to focus on what makes your site different.
baseurl: "/pinax" # the subpath of your site, e.g. /blog/
url: "http://pinaxproject.com" # the base hostname & protocol for your site
twitter_username: pinaxproject
github_username:  pinax

# Build settings
markdown: kramdown
