site_name: Pinax Documentation

pages:
    - "index.md"

    - ["what_is_pinax.md", "Introduction", "What is Pinax?"]
    - ["quick_start.md", "Introduction", "Quick Start"]
    - ["history.md", "Introduction", "History"]
    - ["faq.md", "Introduction", "FAQs"]

    - ["pinax_starter_projects.md", "Starter Projects", "Pinax Starter Projects"]
    - ["starter_project_list.md", "Starter Projects", "List of Starter Projects"]
    - ["moving_to_webpack.md", "Starter Projects", "Moving to webpack"]
    - ["apps_list.md", "Apps", "List of Apps"]

    - ["how_to_contribute.md", "Development", "How to Contribute"]
    - ["code_of_conduct.md", "Development", "Code of Conduct"]
    - ["code_conventions.md", "Development" ,"Code Conventions"]
    - ["release_process.md", "Development", "Release Process"]

    - ["tutorials.md", "Tutorials", "Tutorials"]

theme: readthedocs
