site_name: Pinax Documentation

pages:
    - "index.md"

    - ["what_is_pinax.md", "Introduction", "What is Pinax?"]
    - ["quick_start.md", "Introduction", "Quick Start"]
    - ["history.md", "Introduction", "History"]
    - ["faq.md", "Introduction", "FAQs"]

    - ["starter_project_list.md", "Starter Projects", "List of Starter Projects"]
    - ["apps_list.md", "Apps", "List of Apps"]

    - ["how_to_contribute.md", "Development", "How to Contribute"]
    - ["code_conventions.md", "Development" ,"Code Conventions"]
    - ["release_process.md", "Development", "Release Process"]

    - tutorials.md

theme: readthedocs
