site_name: Pinax Documentation

pages:
    - "index.md"

    - ["what_is_pinax.md", "Introduction", "What is Pinax?"]
    - ["quick_start.md", "Introduction", "Quick Start"]
    - ["history.md", "Introduction", "History"]
    - ["faq.md", "Introduction", "FAQs"]

    - ["pinax_starter_projects.md", "Starter Projects", "Pinax Starter Projects"]
    - ["starter_project_list.md", "Starter Projects", "List of Starter Projects"]
    - ["pinax_theme_bootstrap.md", "Starter Projects", "Pinax Theme Bootstrap"]
    - ["apps_list.md", "Apps", "List of Apps"]

    - ["how-tos/ldap.md", "How Tos", "LDAP Integration"]
    - ["how-tos/deploy-to-heroku.md", "How Tos", "Deploying to Heroku"]

    - ["ways_to_contribute.md", "Development", "Ways to Contribute"]
    - ["code_of_conduct.md", "Development", "Code of Conduct"]
    - ["how_to_contribute.md", "Development" ,"How to Contribute"]
    - ["release_process.md", "Development", "Release Process"]

    - ["tutorials.md", "Tutorials", "Tutorials"]

    - ["in_the_wild.md", "In the Wild", "In the Wild"]

theme: readthedocs
